language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm-nightly

before_install:
    - sudo kill -9 -1

script:
  - phpunit --coverage-text
  - phpunit --group unicode --coverage-text
