language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
  - composer update

install:
  - echo $TRAVIS_COMMIT
  - git fetch origin "refs/pull/$TRAVIS_PULL_REQUEST/merge"
  - git rev-parse FETCH_HEAD
  - git fetch origin "refs/pull/$TRAVIS_PULL_REQUEST/head"
  - git rev-parse FETCH_HEAD

script:
  - phpunit --coverage-text
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi;
  - phpunit --group unicode

branches:
  only:
    - master
