language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm-nightly

install:
  - echo $TRAVIS_COMMIT
  - git fetch origin "refs/pull/$TRAVIS_PULL_REQUEST/merge"
  - git rev-parse FETCH_HEAD
  - git fetch origin "refs/pull/$TRAVIS_PULL_REQUEST/head"
  - git rev-parse FETCH_HEAD

script:
  - phpunit --coverage-text
  - phpunit --group unicode --coverage-text
